### PR TITLE
(WIP) OpenCover Support (WIP)

### PR DESCRIPTION
**Pull request by meilke**
I want to use NUnit wrapped in OpenCover so that code coverage reports would be available. Because of the tight coupling of a) generating the NUnit command and b) executing it within a Grunt task, this pull request current is the only way of injecting OpenCover support (apart from duplicating everything here).

What do you think? Specifically about this but also about the approach to the problem I have.

### CODE REVIEW

**Comment by Nylle** [comment]
Great work! I would consider either duplicating code to stay independent or moving (a) out into it#s own package - although the latter might get a little bit confusing.

**Comment by meilke** [comment]
One could think of the following:

1. Create Node (not Grunt) module that creates the NUnit command
2. Use this module in this Grunt task right here
3. Use it also in a grunt-opencover task or something

**Comment by mikeobrien** [comment]
I'm on gulp now so I don't really care either way. I do think in general it would be better to have these as two separate components but I'd be willing to accept anyways if you think its too difficult to do that.

**Comment by meilke** [comment]
Don't think it is too difficult. If you want, I could go ahead and move the NUnit module into its own repo, create its own NPM package, use it here and in a OpenCover wrap around the NUnit console runner.

**Comment by mikeobrien** [comment]
Sounds good, thx.

**Pull request closed without merging**
